# Generated by Django 4.1.4 on 2023-03-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_personaldetails_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='user_details',
            new_name='user_id',
        ),
    ]
