# Generated by Django 4.1.4 on 2023-03-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_details_personaldetails_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
